# cd dv-in-rust
# cargo run -- --scheduler -c ./configug.toml

[scheduler]
addr = "128.100.13.240:2077"
admin_addr = "127.0.0.1:9999"
#disable_early_release = true
#disable_single_read_optimization = true

[sequencer]
addr = "127.0.0.1:19876"

[[dbproxy]]
addr = "128.100.13.212:38875"
#sql_conf = "host=localhost port=33333 dbname=tpcw user=qinsinin"
[dbproxy.db_mock_latency]
begintx = {mean = 0.0025, stddev = 0.005}
endtx = {mean = 0.04, stddev = 0.175}
read = {mean = 0.46, stddev = 0.65}
write = {mean = 0.1225, stddev = 0.425}


[[dbproxy]]
addr = "128.100.13.244:38875"
#sql_conf = "host=localhost port=33333 dbname=tpcw user=qinsinin"
[dbproxy.db_mock_latency]
begintx = {mean = 0.0025, stddev = 0.005}
endtx = {mean = 0.04, stddev = 0.175}
read = {mean = 0.46, stddev = 0.65}
write = {mean = 0.1225, stddev = 0.425}


[[dbproxy]]
addr = "128.100.13.243:38875"
#sql_conf = "host=localhost port=33333 dbname=tpcw user=qinsinin"
[dbproxy.db_mock_latency]
begintx = {mean = 0.0025, stddev = 0.005}
endtx = {mean = 0.04, stddev = 0.175}
read = {mean = 0.46, stddev = 0.65}
write = {mean = 0.1225, stddev = 0.425}


[[dbproxy]]
addr ="128.100.13.242:38875"
#sql_conf = "host=localhost port=33333 dbname=tpcw user=qinsinin"
[dbproxy.db_mock_latency]
begintx = {mean = 0.0025, stddev = 0.005}
endtx = {mean = 0.04, stddev = 0.175}
read = {mean = 0.46, stddev = 0.65}
write = {mean = 0.1225, stddev = 0.425}

[[dbproxy]]
addr = "128.100.13.241:38875"
#sql_conf = "host=localhost port=33333 dbname=tpcw user=qinsinin"
[dbproxy.db_mock_latency]
begintx = {mean = 0.0025, stddev = 0.005}
endtx = {mean = 0.04, stddev = 0.175}
read = {mean = 0.46, stddev = 0.65}
write = {mean = 0.1225, stddev = 0.425}


