# cd dv-in-rust
# cargo run -- --scheduler -c ./confug.toml

[scheduler]
addr = "128.100.13.240:2077"
admin_addr = "127.0.0.1:9999"
#disable_early_release = true
#disable_single_read_optimization = true

[sequencer]
addr = "127.0.0.1:19876"

[[dbproxy]]
addr = "128.100.13.212:38875"
#sql_conf = "host=localhost port=33333 dbname=tpcw user=qinsinin"
# THESE NEEDS TO BE INTEGERS, IN MS
[dbproxy.db_mock_latency]
begintx = {mean = 0, stddev = 0}
endtx = {mean = 1, stddev = 1}
read = {mean = 0, stddev = 0}
write = {mean = 1, stddev = 1}
