apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator-job
spec:
  template:
    spec:
      containers:
      - name: load-generator
        image: load_generator:latest
        command: ["python3", "./client.py", "--port", "2077", "--c_id", "0", "--ip", "10.103.65.33", "--path", "/usr/src/"]
        imagePullPolicy: Never
      restartPolicy: Never

  backoffLimit: 0