[package]
name = "o2versioner"
version = "0.1.0"
authors = ["Lichen Liu <issac.liu@mail.utoronto.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "3"
actix-session = "0.4"
env_logger = "0.8"
log = "0.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["v4"] }
tokio = { version = "0.2.23", features = ["full"] }
mysql_async = { version = "0.25.0" }
