[[dbproxy]]
addr = "dbproxy0-deployment-0.dbproxy0-service.default.svc.cluster.local:38875"
#addr = "172.25.0.66:38875"
#sql_conf = "host=34.70.104.125 port=5432 dbname=tpcw user=postgres password=Abc@123"
[dbproxy.db_mock_latency]
begintx = {mean = 30, stddev = 10}
endtx = {mean = 20, stddev = 10}
read = {mean = 20, stddev = 10}
write = {mean = 30, stddev = 10}
