[scheduler]
addr = "127.0.0.1:2077"
admin_addr = "127.0.0.1:9999"
disable_early_release = true
dispatcher_queue_size = 500
performance_loggin = "./logging"
sequencer_pool_size = 10
transceiver_queue_size = 10

[sequencer]
addr = "127.0.0.1:9876"

# This is for UG
[[dbproxy]]
addr = "127.0.0.1:8875"
dbname = "tpcw"
host = "34.70.104.125"
password = "Abc@123"
port = "5432"
user = "postgres"

# This is for Isac
[[dbproxy]]
addr = "127.0.0.1:8876"
dbname = "tpcw"
host = "34.69.18.204"
password = "Abc@123"
port = "5432"
user = "postgres"
