[scheduler]
addr = "127.0.0.1:1077"

[sequencer]
addr = "127.0.0.1:9876"

[[dbproxy]]
addr = "127.0.0.1:8876"
sql_addr = "mysql://root:Rayh8768@localhost:3306/test"

[[dbproxy]]
addr = "127.0.0.1:8877"
sql_addr = "mysql://root:Rayh8768@localhost:3306/test"

[[dbschemas]]
table_name = "table1"

[[dbschemas]]
table_name = "table2"
