[scheduler]
addr = "127.0.0.1:1077"
admin_addr = "127.0.0.1:9999"
performance_loggin = "./logging"
dispatcher_queue_size = 500
max_connection = 50
sequencer_pool_size = 20
transceiver_queue_size = 20
disable_early_release = true

[sequencer]
addr = "127.0.0.1:9876"
max_connection = 50

# This is for UG
[[dbproxy]]
addr = "127.0.0.1:8875"
dbname = "tpcw"
host = "34.70.104.125"
password = "Abc@123"
port = "5432"
user = "postgres"

# This is for Isac
[[dbproxy]]
addr = "127.0.0.1:8876"
dbname = "tpcw"
host = "34.69.18.204"
password = "Abc@123"
port = "5432"
user = "postgres"




