apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
      annotations:
        k8s.v1.cni.cncf.io/networks: db-in-k8s
        k8s.v1.cni.cncf.io/networks-status: |- 
          [{
              "ips": [
                  "172.25.0.65"
              ],
          }]
    spec: 
      containers:
        - name: scheduler
          image: systems:latest
          command: ["./systems_start.sh"]
          imagePullPolicy: Never
          ports:
          - containerPort: 2077
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  clusterIP: 10.96.149.230
  selector:
    app: scheduler
  # type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 2077
      targetPort: 2077
