apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec: 
  serviceName: scheduler-service
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
      annotations:
        k8s.v1.cni.cncf.io/networks: db-in-k8s
        k8s.v1.cni.cncf.io/networks-status: |- 
          [{
              "ips": [
                  "172.25.0.65"
              ],
          }]
    spec: 
      containers:
        - name: scheduler
          image: systems:latest
          command: ["./systems_start.sh"]
          imagePullPolicy: Never
          ports:
          - containerPort: 2077
            name: sched-container
          - containerPort: 9999
            name: admin-container
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  clusterIP: None
  selector:
    app: scheduler
  # type: LoadBalancer  
  ports:
    - name: scheduler-port
      protocol: TCP
      port: 2077
      targetPort: 2077
    - name: admin-port
      protocol: TCP
      port: 9999
      targetPort: 9999