name: o2versioner-build

on:
  push:
    branches: [ main ]
    paths:
      - 'o2versioner/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'o2versioner/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
